fix whitespace/indentation errors
Some lines are indented by spaces, while adjacent lines are indentet by tabs.
We should use tabs on both.

Signed-off-by: Erich Eckner <git@eckner.net>

diff --git a/mkarchroot.in b/mkarchroot.in
--- a/mkarchroot.in
+++ b/mkarchroot.in
@@ -86,7 +86,7 @@ for file in "${files[@]}"; do
 done
 
 pacstrap -Mcd ${pac_conf:+-C "$pac_conf"} "$working_dir" \
-  "${cache_dirs[@]/#/--cachedir=}" "$@" || die 'Failed to install all packages'
+	"${cache_dirs[@]/#/--cachedir=}" "$@" || die 'Failed to install all packages'
 
 printf '%s.UTF-8 UTF-8\n' en_US de_DE > "$working_dir/etc/locale.gen"
 echo 'LANG=en_US.UTF-8' > "$working_dir/etc/locale.conf"
